from __future__ import annotations

from dataclasses import dataclass


MEBIBYTE = 1024 * 1024
GIBIBYTE = 1024 * MEBIBYTE

MAX_JSONL_BYTES = 64 * MEBIBYTE
MAX_JSONL_LINE_BYTES = MEBIBYTE
MAX_JSONL_RECORDS = 100_000

MAX_BUNDLE_ARCHIVE_BYTES = 8 * GIBIBYTE
MAX_BUNDLE_MEMBERS = 10_000
MAX_BUNDLE_MEMBER_BYTES = 4 * GIBIBYTE
MAX_BUNDLE_TOTAL_BYTES = 16 * GIBIBYTE
MAX_BUNDLE_CONTROL_BYTES = 64 * MEBIBYTE
MAX_BUNDLE_COMPRESSION_RATIO = 200.0


@dataclass(frozen=True)
class Settings:
    max_files: int = 5000
    include_hidden: bool = False
